name = "TerminalSystemMonitor"
uuid = "bd0a793d-05ca-4aa9-be12-7c4786d45f63"
authors = ["Satoshi Terasaki <terasakisatoshi.math@gmail.com>"]
version = "0.0.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
MLDataDevices = "7e8f7934-dd98-4c1a-8fe8-92b47a384d40"
Term = "22787eb5-b846-44ae-b979-8e399b8463ab"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[extensions]
TerminalSystemMonitorCUDAExt = ["CUDA"]

[compat]
CUDA = "5.5.2"
Dates = "1"
MLDataDevices = "1.5.3"
Term = "2.0.6"
UnicodePlots = "3.7.0"
julia = "1"
